# Generated by Django 4.2.2 on 2023-07-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_subject_created_at_staff_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
